export const GET_FILMS = 'GET_FILMS';
export const LOADING_FILMS = 'LOADING_FILMS';

export const GET_FILM = 'GET_FILM';
export const LOADING_FILM = 'LOADING_FILM';

export const GET_STARSHIP = 'GET_STARSHIP';
export const LOADING_STARSHIP = 'LOADING_STARSHIP';

export const GET_STARSHIPFAV ='GET_STARSHIPFAV';
export const ADD_STARSHIPFAV ='ADD_STARSHIPFAV';
export const DELETE_STARSHIPFAV ='DELETE_STARSHIPFAV';
export const STARSHIPFAV_LOADING ='STARSHIPFAV_LOADING';
